name: mri-qrf
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - pandas
  - openpyxl
  - pillow
  - nibabel
  - scipy
  - scikit-learn
  - joblib
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - torch
      - torchvision
